# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 171fcd014d16e320d3f91c24e7375865b29d1892d660e46bd10f36c1e87885aea1b06a169e24a9a39d3bab328ef7126c896c7e5ba3ac320b586244e77399e762

test:
  secret_key_base: 30f0068b4a30cd8d1b6949ae9425ec6c5c65e93ab273d7434190c1588efa3a357e61c7523898cadb1652dfc3ca64c1b67f8fc7963858c459b3d89cb00bfdb53b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
